### ISSUE TITLE
sqlserver-odbcdriver needs to be updated to 14.0.3048.4

### ISSUE THREAD

**Issue by brianary** [Roemer/Chocolatey-Packages#12]
Version 14.0.3048.4 of **msodbcsql.msi** (SHA256 42B5AFEFDAF69982C319C94D7B1398E2399F4C409AE1B5B6F27A31752E7D149D) is available, but I've only been able to find it within [**SQLServer2017-KB4466404-x64.exe**](https://support.microsoft.com/help/4466404/cumulative-update-13-for-sql-server-2017 "Cumulative Update 13 for SQL Server 2017") if I open it with 7-zip (in the _1033_enu_lp\x64\setup\x64_ folder). I can't find a separate download.

**Comment by Roemer** [comment]
I just updated the package to 17.3.1.1 and embedded the msi files so it will never break in the future.

**Comment by brianary** [comment]
Just to clarify, RedGate's SQL Change Automation (part of the **sqltoolbelt** choco package) requires the **SQLLocalDB** choco package, which requires a very specific version of the **msodbcsql.msi** driver (the one mentioned above). Later major versions don't work, and lesser build numbers of v14 doesn't work either.
