### ISSUE TITLE
sqlserver-odbcdriver 17.3.1.1 not available on chocolatey

### ISSUE THREAD

**Issue by OskarPersson** [Roemer/Chocolatey-Packages#15]
I can't find version 17.3.1.1 of sqlserver-odbcdriver on chocolatey, is there a reason for this?

**Comment by Roemer** [comment]
I wanted to push them with the msi (installer) embedded but Microsoft failed to provide a licence for it. I now reverted the packages to download the installers on the fly. I pushed the refreshed versions to chocolatey now.
