### ISSUE TITLE
Microsoft download link broken.

### ISSUE THREAD

**Issue by sutarsha** [Roemer/chocolatey-packages#18]
Hi Team,

Greetings for the day!!

We are using sqlserver-cmdlineutils chocolatey package in our automation and it downloads the file from https://download.microsoft.com/download/E/6/B/E6BFDC7A-5BCD-4C51-9912-635646DA801E/en-US/msodbcsql17.5.1.1x64.msi which is broken. 
The correct link for download is https://download.microsoft.com/download/E/6/B/E6BFDC7A-5BCD-4C51-9912-635646DA801E/en-US/17.5.2.1/x64/msodbcsql.msi

Request you to update the chocolatey package with the updated URL mentioned above.

Many Thanks!!

Regards,
Shailesh

**Comment by Roemer** [comment]
There is a new package version `15.0.1300.359001` which should fix the issue.

**Comment by sutarsha** [comment]
Issue is fixed by upgrading the version. Thanks a lot!
