### ISSUE TITLE
sqlserver-cmdlineutils version 13.1 outdated links

### ISSUE THREAD

**Issue by radoslaf85** [Roemer/chocolatey-packages#24]
Hi,

Can you please update the URL for download of Microsoft SQL Server 2012 Command Line Utilities?

New
https://download.microsoft.com/download/C/8/E/C8ECE442-C29C-4EE4-BD73-872C03D9EB84/ENG_1033/x64/SqlCmdLnUtils.msi
Old
https://download.microsoft.com/download/C/8/8/C88C2E51-8D23-4301-9F4B-64C8E2F163C5/Command%20Line%20Utilities%20MSI%20files/amd64/MsSqlCmdLnUtils.msi
New
https://download.microsoft.com/download/C/8/E/C8ECE442-C29C-4EE4-BD73-872C03D9EB84/ENG_1033/x86/MsSqlCmdLnUtils.msi
Old
https://download.microsoft.com/download/C/8/8/C88C2E51-8D23-4301-9F4B-64C8E2F163C5/Command%20Line%20Utilities%20MSI%20files/x86/MsSqlCmdLnUtils.msi

It seems you are building only new version so I don't know how to update the code.

**Comment by Roemer** [comment]
A new version is released so that should be fixed.
