### ISSUE TITLE
freerdp package outdated

### ISSUE THREAD

**Issue by pauby** [Roemer/chocolatey-packages#27]
Hi, the [`freerdp`](https://community.chocolatey.org/packages/freerdp) package is very outdated. Another package called [`freerdp.portable`](https://community.chocolatey.org/packages/freerdp.portable) is now the latest version of `freerdp`. Can you either update your package, and we can look to deprecate `freerdp.portable` or can you [deprecate your package](https://docs.chocolatey.org/en-us/community-repository/maintainers/deprecate-a-chocolatey-package) in favour of `freerdp.portable`?

**Comment by gep13** [comment]
@Roemer Just wanted to follow up with this.  Is this something that you would be in a position to do?

**Comment by Roemer** [comment]
My problem with freerdp is that there are no official newer Windows builds than what my package still contains. There are just nightly builds which might match a version more or less. If that is good enough, we can go both routes: Deprecating this package or update it.

**Comment by gep13** [comment]
@Roemer thank you for replying!

Just to check, are we talking about the same package/application here?

Currently, your Chocolatey Package for FreeRDP (https://community.chocolatey.org/packages/freerdp) is at version 1.1, but following through to the Software Site (http://www.freerdp.com/) there is a version 2.9.0 of the application, which was published on November 2022.

**Comment by Roemer** [comment]
Yes that is correct. But there is no Windows Binary available for FreeRDP > 1.1. The best that is available (officially) is a nightly package at the day of the release.

**Comment by gep13** [comment]
Oh, I see! Which is where your comment about `nightly builds` comes into play, as this is what is being used in this package: 

https://community.chocolatey.org/packages/freerdp.portable

@pauby what are your thoughts here?

**Comment by pauby** [comment]
@gep13 and I discussed it this morning. It all makes sense now 😄 

I think what we should do is submit a package fix version for this package, outlining that it is the stable versions of freerdp that are being targetted. This will differentiate it from the `freerdp.portable` package which is targetting nightly releases which _look like to be_ not from an official source.

We will then have two packages:

- `freerdp`: latest Windows official stable version.
- `freerdp.portable`: nightly builds not from an official source.

@Roemer I will submit a PR to you to update this package with the minor updates if you are happy to merge and push it?

**Comment by Roemer** [comment]
Yes that is absolutely fine. I hope some day we get official new releases from FreeRDP...

**Comment by pauby** [comment]
Submitted [PR](https://github.com/Roemer/chocolatey-packages/pull/30) and asked @gep13 to confirm I haven't missed anything obvious.

**Comment by pauby** [comment]
@Roemer Can we look to get the PR merged in?

**Comment by Roemer** [comment]
@pauby ah dang, my comment was in pending state. Just published it. Should we really create a new version?

**Comment by Roemer** [comment]
I just pushed the new package.
