### ISSUE TITLE
Update of sqlserver-odbcdriver package?

### ISSUE THREAD

**Issue by fdcastel** [Roemer/chocolatey-packages#31]
Greetings, fellow package mantainer!

[Community](https://github.com/Roemer/chocolatey-packages/commit/250d47e5f4986f94ec426d6827f247f762f7d33c#commitcomment-90361114) (including, me!) wants to cordially ask you for a few minutes of you time to push the latest version of `sqlserver-odbcdriver` package to chocolatey public repository 😄.

If it helps, I have a (non-official) version [here](https://github.com/fdcastel/chocolatey-packages/tree/master/msodbcsql) with the latest version urls and hashs. (I use it in my private servers only, and I like the shorter name).

Speaking of: I also had a little chat with @pauby today about the package naming [on discord](https://discord.com/channels/778552361454141460/897090709914517544/1104429758424555620) and I would like to hear your opinion about the subject. 

All that said, I see that others are [asking you the same](http://disq.us/p/2ryf6gt) for some time now. And as a package maintainer I also know that requests like this could arrive not always in the best of times. So, if you wish, I would be glad to help you with the tasks.

Kind regards!

**Comment by Roemer** [comment]
Hello
I already published an 18.x version and now updated to the latest version.
Last time it seems it got rejected by chocolatey. Let's see if it gets thru
this time or what is the issue. If you want to help keeping it updated,
next time just send a Pull-Request over at GitHub with the new version and
download links. Then it takes me only a few minutes to publish it.
Regards
Roman

Am Sa., 6. Mai 2023 um 18:49 Uhr schrieb F.D.Castel <
***@***.***>:

**Comment by fdcastel** [comment]
Just for the sake of curiosity: The rejection from chocolatey automated tests was caused by an 1603 MSI error?

**Comment by Roemer** [comment]
Unfortunately I don't remember but the new one was accepted!

Am Sa., 6. Mai 2023 um 22:49 Uhr schrieb F.D.Castel <
***@***.***>:

**Comment by Roemer** [comment]
I'll close this as it is updated. Feel free to create a new if another update is missing or even better, create a PR with the new version.
