### ISSUE TITLE
sqlserver-odbcdriver: Separate Package Per Version

### ISSUE THREAD

**Issue by tannerwatson** [Roemer/chocolatey-packages#32]
With Chocolatey looking to chocolatey/choco#2787 are you all looking to publish a separate package per version of `sqlserver-odbcdriver`? If it's not on the radar can I contribute for the publishing of the separate packages?

I have some requirements where multiple versions are needed to be present on boxes.

**Comment by ScottMonolith** [comment]
@tannerwatson - I would also be interested in having separate ODBC driver packages - have you made any progress here, anything I can do to assist?  .NET Runtime has this already (IE dotnet-7.0-runtime, dotnet-6.0-runtime, dotnet-5.0-runtime) and I likewise have a need for the v17 ODBC driver.  It is still receiving updates from Microsoft as well.

CC @Roemer

**Comment by Roemer** [comment]
Hmm what would that look like? like a package for each version?
like `sqlserver-odbcdriver-18.3.1.1` or for main versions `sqlserver-odbcdriver-18`? I feel this gets kind of messy.

**Comment by ScottMonolith** [comment]
@Roemer - I would vote you do this similar to how .NET does it.  The 'newest' stable version remain at `sqlserver-odbcdriver`, the 'old' version would be `sqlserver-17-odbcdriver`.  So whenever v19 comes out, you can keep the naming convention and just add version numbers for older versions (assuming they are still getting updates - I wouldn't expect older versions that are not getting updated to be maintained).

For example, the .NET SDK - `dotnet-5.0-sdk`, `dotnet-6.0-sdk`, and then the latest is just `dotnet-sdk`.

**Comment by Roemer** [comment]
I did this just now.
There is now:
- https://community.chocolatey.org/packages/sqlserver-odbcdriver-17 for v17
- https://community.chocolatey.org/packages/sqlserver-odbcdriver-18 for v18
- https://community.chocolatey.org/packages/sqlserver-odbcdriver which will now be a meta package, always pointing to the latest version

**Comment by Roemer** [comment]
I think this is solved now.
