### ISSUE TITLE
sqlserver-cmdlineutils download location changed with the release of 14.0

### ISSUE THREAD

**Issue by jagregory** [Roemer/Chocolatey-Packages#4]
FYI, the sqlserver-cmdlineutils package is currently failing because the download URLs have changed to:

x86: https://download.microsoft.com/download/C/8/8/C88C2E51-8D23-4301-9F4B-64C8E2F163C5/x86/MsSqlCmdLnUtils.msi
x64: https://download.microsoft.com/download/C/8/8/C88C2E51-8D23-4301-9F4B-64C8E2F163C5/x64/MsSqlCmdLnUtils.msi

**Comment by Roemer** [comment]
Fixed and new package uploaded.
