### ISSUE TITLE
Deprecate NUnit package in favour of Nunit.org packages

### ISSUE THREAD

**Issue by ChrisMaddock** [Roemer/Chocolatey-Packages#7]
Hi!

I've noticed you have a package for the nunit console. Since this was put online, the NUnit team have added chocolatey packaging into the release process - and now release a chocolatey package at the same time as every general software release is made.

I noticed your package was a few versions behind at the moment. Would you accept a pull request to [deprecate](https://chocolatey.org/docs/how-to-deprecate-a-chocolatey-package) this package, in favour of the nunit.org package? I'd be happy to submit that PR - we're always keen people are getting the latest version of NUnit in the easiest way possible! 😄

**Comment by Roemer** [comment]
Yes of course! Feel free to create a PR and I will publish it.

**Comment by ChrisMaddock** [comment]
Brilliant, thanks! Will get it sorted some time in the next week! 😊
